project:
  type: website
  output-dir: docs

website:
  title: "SDS390"
  favicon: 390.png
  navbar:
    left:
      - text: "FPP"
        href: https://otexts.com/fpp3/
      - text: "DC"
        href: https://app.datacamp.com/learn/assignments
      - text: "ChatGPT"
        href: https://chat.openai.com/
      - text: "Problem Sets"
        href: PS.html      
      - text: "Final Project"
        href: final_project.html   
    right:
      - text: "Roster"
        href: https://docs.google.com/spreadsheets/d/12GJWpG53UQgVwG-TEms5uT88HKSkh-m3g81k63SV_YA/edit#gid=0
      - text: "Screencasts"
        href: https://drive.google.com/drive/u/1/folders/1ctkp8FthWTOSvCZfEZAl63XtCZA5c8KV
      - text: "Moodle"
        href: https://moodle.smith.edu/course/view.php?id=47365 
      - text: "Syllabus"
        href: https://docs.google.com/document/d/1pYACVZ91x21ffbMDfCgFGqvjM0v9YFiTSGX2-TwHUNE/edit#heading=h.amnifumas6q




format:
  html:
    theme: cosmo
    css: styles.css
    highlight: tango
    toc: true
    toc_float: true
    toc_collapsed: false
    toc_depth: 1
    df_print: paged


editor: visual

