---
title: "Problem Sets"
---



# Problem Set 2

1.  [Slides](PS/dendrobands.pdf) on PS02 data's context. Prof Kim quote: "Numbers are numbers, but data has context"
2.  My thoughts about ChatGPT. It is a very powerful tool, but you need to be:
    1.  Knowledgeable enough to understand the code
    2.  Experienced enough in your domain and programming to know what to prompt
    3.  Disciplined enough to sanity check your results


## Instructions

1. Posted on Slack under `#questions`
1. Individual `PS01.ipynb` files
    1. Complete `PS02.ipynb` by Tue 10/24 class time
    1. Due Thu 10/26 9:25am on Moodle
1. In-class on Thu 10/5: "Think, Pair, Share" exercise



***



# Problem Set 1

## Instructions

1.  Posted on Slack under `#questions`
2.  Individual `PS01.ipynb` files
    1.  Due Thu 10/5 9:25am on moodle (see Moodle link on top right of page)
    2.  Submit both a `PS01.ipynb` where all code is reproducible and a `.csv` file of your data
3.  In-class on Thu 10/5: "Think, Pair, Share" exercise
    1.  I will randomly create teams of pairs. Any remaining odd number student will be paired with me.
    2.  You will show each other your code and prepare a single mini-presentation `.ipynb`
    3.  I will pick 2-3 pairs at random to present their work in front of the class
    4.  You will rate your peer's preparation using this [Google Form](https://docs.google.com/forms/d/e/1FAIpQLSe6uHGVCgcHwBae-k00k6GXxmWKAhouNWivH-3NSim020bgww/viewform)

Clarifications added afterwards:

1.  Dataset should be at least 100 rows
2.  For mini-presentation, you will have to choose one of the two datasets
3.  Do problem set in python


## In-Class Presentations

1.  I will make groups at random using code below. I will join a group if there is an odd person left out.
2.  Work together for 20 minutes to come up with single `.ipynb`
3.  I will pick two teams at random to present to the class
4.  I will present my work to the class. click [here](https://github.com/rudeboybert/SDS390/blob/master/PS/PS01_albert.ipynb)
5.  Answer the sli.do poll [here](https://app.sli.do/event/3x3vyqpgVxaVxm6XTJLxxF)
6.  Rate your peer's preparation using this [Google Form](https://docs.google.com/forms/d/e/1FAIpQLSe6uHGVCgcHwBae-k00k6GXxmWKAhouNWivH-3NSim020bgww/viewform)
Code to generate groups:

```{r, eval = FALSE}
library(tidyverse)
read_csv("390.csv") %>% 
  filter(First != "Albert") %>% 
  sample_frac(1) %>% 
  mutate(team = rep(1:9, length = 17)) %>% 
  arrange(team)

read_csv("390.csv") %>% 
  filter(First != "Albert") %>% 
  sample_n(2)
```

`***` = presented

```         
 1 Yang           Christy        1
 2 O'Meara        Abbey          1
 3 Slosser        Tillie         2 ***
 4 Murray         Kiera          2 ***
 5 Khan           Nubraz         3
 6 Ding           Jenny          3
 7 Anesko         Greta          4
 8 Martin         Teddy          4
 9 Xu             Xiaoman        5
10 An             Rachael        5
11 Kogalovski     Aleksandra     6
12 Qiu            Chi            6
13 Knecht         Beata          7 ***
14 Basnet Chettri Charavee       7 ***
15 Tha Ra Wun     Tint           8
16 Huang          Juniper        8
17 Pu             Betty          9
```


## Example Solutions

1. Tillie + Kiera and Beata + Charavee's solutions [here](PS/PS01_presentations.zip)
1. Prof Kim's [solution](https://github.com/rudeboybert/SDS390/blob/master/PS/PS01_albert.ipynb)


